# Generated by Django 5.2.8 on 2025-11-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
