# Generated by Django 5.2.8 on 2025-11-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_group', '0003_product_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_services',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product_services',
            name='product_service_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
