# Generated by Django 5.2.8 on 2025-11-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_group', '0004_product_services_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='product_group_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
