# Generated by Django 5.2.8 on 2025-11-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_group', '0005_alter_productgroup_product_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_services',
            name='unit',
        ),
    ]
