# Generated by Django 5.2.8 on 2025-12-01 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('product_group', '0007_quote_quoteitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='client_name',
        ),
        migrations.AddField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='client.company'),
        ),
    ]
