# Generated by Django 5.2.8 on 2025-12-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='in_house_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quote',
            name='invoiced_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quote',
            name='outsourced_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quote',
            name='to_be_invoiced_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quote',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
