# Generated by Django 5.2.8 on 2025-12-09 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('product_group', '0002_quote_in_house_cost_quote_invoiced_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='poc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='client.poc'),
        ),
    ]
