# Generated by Django 5.2.8 on 2025-12-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_group', '0003_quote_poc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('Oppurtunity', 'Oppurtunity'), ('Scoping', 'Scoping'), ('Proposal', 'Proposal'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Oppurtunity', max_length=20),
        ),
    ]
