# Generated by Django 5.2.8 on 2026-01-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_group', '0004_alter_quote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='product_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product_group.product_services'),
            preserve_default=False,
        ),
    ]
