# Generated by Django 5.2.8 on 2026-01-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_group', '0005_alter_quoteitem_product_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='is_outsourced',
            field=models.BooleanField(default=False, help_text='If true, this item requires Purchase Order'),
        ),
    ]
