# Generated by Django 5.2.8 on 2026-01-27 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_company_gstin_alter_company_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='mobile_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number.', regex='^[0-9+\\-\\s()]{7,10}$')]),
        ),
    ]
