# Generated by Django 5.2.8 on 2026-01-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('product_group', '0005_alter_quoteitem_product_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('vendor_type', models.CharField(choices=[('freelancer', 'Freelancer'), ('company', 'Company')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_groups', models.ManyToManyField(blank=True, related_name='vendors', to='product_group.productgroup')),
            ],
        ),
    ]
