# Generated by Django 5.2.8 on 2025-11-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordresetotp',
            name='accounts_pa_email_d46b34_idx',
        ),
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='email',
            new_name='gmail',
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['gmail', 'code'], name='accounts_pa_gmail_188a13_idx'),
        ),
    ]
