# Generated by Django 5.2.8 on 2025-11-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
