# Generated by Django 5.2.8 on 2025-11-24 09:58

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_gmail'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordresetotp',
            name='accounts_pa_gmail_188a13_idx',
        ),
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='code',
        ),
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='gmail',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='code_hash',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['user', 'created_at'], name='accounts_pa_user_id_c7ab27_idx'),
        ),
    ]
