# Generated by Django 5.2.8 on 2025-11-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
