# Generated by Django 5.2.8 on 2025-11-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_module_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='updated_by',
            new_name='modified_by',
        ),
    ]
