# Generated by Django 5.2.8 on 2025-12-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_project_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbudget',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectbudget',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget', to='Project.project'),
        ),
    ]
