# Generated by Django 5.2.8 on 2025-12-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_remove_projectbudget_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('development', 'Development In Progress'), ('testing', 'Testing In Progress'), ('uat', 'UAT In Progress'), ('ready_for_deployment', 'Ready for Deployment'), ('deployed', 'Deployed'), ('on_hold', 'On Hold')], default='planning', max_length=50),
        ),
    ]
