# Generated by Django 5.2.8 on 2025-12-23 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_alter_task_created_by_alter_task_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='Project.task'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='timesheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='Project.timesheet'),
        ),
    ]
