# Generated by Django 5.2.8 on 2025-12-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_taskextrahoursrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskextrahoursrequest',
            name='approved_allocated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='taskextrahoursrequest',
            name='previous_allocated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
