# Generated by Django 5.2.8 on 2025-12-29 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_taskextrahoursrequest_approved_allocated_hours_and_more'),
        ('product_group', '0004_alter_quote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_from_quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='product_group.quote'),
        ),
    ]
