# Generated by Django 5.2.8 on 2026-01-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0012_alter_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktimerlog',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
    ]
