# Generated by Django 5.2.8 on 2025-12-31 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0012_alter_project_created_from_quotation'),
        ('Project', '0012_alter_project_project_name'),
    ]

    operations = [
    ]
