# Generated by Django 5.2.8 on 2026-01-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0013_merge_20251231_1115'),
        ('Project', '0013_tasktimerlog_is_extra'),
    ]

    operations = [
    ]
