# Generated by Django 5.2.8 on 2026-01-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0014_merge_20260108_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskextrahoursrequest',
            name='requested_hours',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
