# Generated by Django 5.2.8 on 2026-01-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0015_alter_taskextrahoursrequest_requested_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='hours',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
