# Generated by Django 5.2.8 on 2026-01-30 06:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_alter_timesheetentry_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbudget',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='tax_type',
            field=models.CharField(choices=[('none', 'No Tax'), ('gst', 'GST'), ('vat', 'VAT')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='total_cost_with_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
