# Generated by Django 5.2.8 on 2026-01-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0017_projectbudget_tax_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbudget',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='projectbudget',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='projectbudget',
            name='tax_type',
        ),
        migrations.RemoveField(
            model_name='projectbudget',
            name='total_cost_with_tax',
        ),
    ]
