# Generated by Django 5.2.8 on 2025-11-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_add_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['category__permission_category_name', 'label']},
        ),
        migrations.AlterModelOptions(
            name='permissioncategory',
            options={'ordering': ['permission_category_name'], 'verbose_name_plural': 'Permission Categories'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['role_name']},
        ),
        migrations.RenameField(
            model_name='permissioncategory',
            old_name='name',
            new_name='permission_category_name',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role_name',
        ),
    ]
