# Generated by Django 5.2.8 on 2025-12-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poc_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=100)),
                ('poc_mobile', models.CharField(max_length=20)),
                ('poc_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocs', to='client.company')),
            ],
        ),
    ]
