# Generated by Django 5.2.8 on 2025-12-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_poc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
