# Generated by Django 5.2.8 on 2025-12-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='poc_designation',
        ),
        migrations.RemoveField(
            model_name='company',
            name='poc_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='poc_mobile',
        ),
        migrations.RemoveField(
            model_name='company',
            name='poc_name',
        ),
    ]
