# Generated by Django 5.2.8 on 2025-12-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_company_poc_designation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poc',
            unique_together={('company', 'poc_name', 'poc_mobile', 'poc_email')},
        ),
    ]
