# Generated by Django 5.2.8 on 2025-12-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_poc_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='poc_mobile',
            field=models.CharField(max_length=15),
        ),
    ]
