# Generated by Django 5.2.8 on 2026-01-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_invoice_discount_amount_invoice_pdf_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemilestone',
            name='id',
        ),
        migrations.AlterField(
            model_name='invoicemilestone',
            name='milestone_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
