# Generated by Django 5.2.8 on 2026-01-05 07:51

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0013_merge_20251231_1115'),
        ('client', '0001_initial'),
        ('finances', '0004_remove_invoicemilestone_id_and_more'),
        ('product_group', '0005_alter_quoteitem_product_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoicemilestone',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='invoicemilestone',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoicepayment',
            name='milestone',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Issued', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='invoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('balance_amount__gte', 0)), name='invoice_balance_non_negative'),
        ),
        migrations.DeleteModel(
            name='InvoiceMilestone',
        ),
    ]
