# Generated by Django 5.2.8 on 2026-01-08 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendor'),
        ('finances', '0006_invoice_cancelled_at_invoice_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vendor'),
        ),
        migrations.AlterField(
            model_name='outgoingpayment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vendor'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
