# Generated by Django 5.2.8 on 2026-01-29 09:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_alter_timesheetentry_hours'),
        ('accounts', '0004_account_currency'),
        ('finances', '0008_projectattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_no', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('travel', 'Travel'), ('food', 'Food'), ('internet', 'Internet'), ('electricity', 'Electricity'), ('software', 'Software'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=30)),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.project')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vendor')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('upi', 'UPI'), ('cash', 'Cash'), ('card', 'Card')], max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finances.expense')),
            ],
        ),
    ]
