# Generated by Django 5.2.8 on 2025-11-24 12:04

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('roles', '0001_initial'),
#     ]

#     operations = [
#     ]


from django.db import migrations


def seed(apps, schema_editor):
    PermissionCategory = apps.get_model("roles", "PermissionCategory")
    Permission = apps.get_model("roles", "Permission")

    c_users = PermissionCategory.objects.create(name="User Management")
    c_roles = PermissionCategory.objects.create(name="Role Management")
    c_rbac  = PermissionCategory.objects.create(name="RBAC Core")

    permissions = [
        ("user.create", "Create User", c_users),
        ("user.view", "View Users", c_users),
        ("user.update", "Update User", c_users),
        ("user.delete", "Delete User", c_users),
        ("roles.create", "Create Role", c_roles),
        ("roles.view", "View Role", c_roles),
        ("roles.update", "Update Role", c_roles),
        ("roles.delete", "Delete Role", c_roles),
        ("rbac.permissions.view", "View Permission Catalog", c_rbac),
    ]

    for code, label, cat in permissions:
        Permission.objects.get_or_create(
            code=code,
            defaults={"label": label, "category": cat},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0001_initial"),
    ]
    operations = [
        migrations.RunPython(seed),
    ]
 