# Generated by Django 5.2.8 on 2025-11-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_role_unique_role_role_name_case_insensitive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
    ]
